/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.domain.jooq;


import com.anarbek.shop.dao.domain.jooq.tables.Characteristic;
import com.anarbek.shop.dao.domain.jooq.tables.CharacteristicValue;
import com.anarbek.shop.dao.domain.jooq.tables.Customer;
import com.anarbek.shop.dao.domain.jooq.tables.Image;
import com.anarbek.shop.dao.domain.jooq.tables.Measurement;
import com.anarbek.shop.dao.domain.jooq.tables.Product;
import com.anarbek.shop.dao.domain.jooq.tables.ShopUser;
import com.anarbek.shop.dao.domain.jooq.tables.ShopUserRoles;
import com.anarbek.shop.dao.domain.jooq.tables.records.CharacteristicRecord;
import com.anarbek.shop.dao.domain.jooq.tables.records.CharacteristicValueRecord;
import com.anarbek.shop.dao.domain.jooq.tables.records.CustomerRecord;
import com.anarbek.shop.dao.domain.jooq.tables.records.ImageRecord;
import com.anarbek.shop.dao.domain.jooq.tables.records.MeasurementRecord;
import com.anarbek.shop.dao.domain.jooq.tables.records.ProductRecord;
import com.anarbek.shop.dao.domain.jooq.tables.records.ShopUserRecord;
import com.anarbek.shop.dao.domain.jooq.tables.records.ShopUserRolesRecord;
import com.anarbek.shop.dao.domain.jooq.tables.records.СharacteristicRecord;
import com.anarbek.shop.dao.domain.jooq.tables.records.СharacteristicValueRecord;
import com.anarbek.shop.dao.domain.jooq.tables.Сharacteristic;
import com.anarbek.shop.dao.domain.jooq.tables.СharacteristicValue;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<CharacteristicRecord> CHARACTERISTIC_PKEY = UniqueKeys0.CHARACTERISTIC_PKEY;
	public static final UniqueKey<CharacteristicValueRecord> CHARACTERISTIC_VALUE_PKEY = UniqueKeys0.CHARACTERISTIC_VALUE_PKEY;
	public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = UniqueKeys0.CUSTOMER_PKEY;
	public static final UniqueKey<ImageRecord> IMAGE_PKEY = UniqueKeys0.IMAGE_PKEY;
	public static final UniqueKey<MeasurementRecord> MEASUREMENT_PKEY = UniqueKeys0.MEASUREMENT_PKEY;
	public static final UniqueKey<ProductRecord> PRODUCT_PKEY = UniqueKeys0.PRODUCT_PKEY;
	public static final UniqueKey<ShopUserRecord> SHOP_USER_PKEY = UniqueKeys0.SHOP_USER_PKEY;
	public static final UniqueKey<ShopUserRecord> UK_6REHGURDH18GNR2DBVRYVVDEF = UniqueKeys0.UK_6REHGURDH18GNR2DBVRYVVDEF;
	public static final UniqueKey<СharacteristicRecord> СHARACTERISTIC_PKEY = UniqueKeys0.СHARACTERISTIC_PKEY;
	public static final UniqueKey<СharacteristicValueRecord> СHARACTERISTIC_VALUE_PKEY = UniqueKeys0.СHARACTERISTIC_VALUE_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<CharacteristicRecord, MeasurementRecord> CHARACTERISTIC__FK_NNSCUVJNXX4K3LEQ8XV03E7V3 = ForeignKeys0.CHARACTERISTIC__FK_NNSCUVJNXX4K3LEQ8XV03E7V3;
	public static final ForeignKey<CharacteristicValueRecord, CharacteristicRecord> CHARACTERISTIC_VALUE__FK_JX672GO7SRNA7S8WJWNYKCLS9 = ForeignKeys0.CHARACTERISTIC_VALUE__FK_JX672GO7SRNA7S8WJWNYKCLS9;
	public static final ForeignKey<CharacteristicValueRecord, ProductRecord> CHARACTERISTIC_VALUE__FK_8RVXP5IF9WE3HNY0G41CQFVFN = ForeignKeys0.CHARACTERISTIC_VALUE__FK_8RVXP5IF9WE3HNY0G41CQFVFN;
	public static final ForeignKey<ImageRecord, ProductRecord> IMAGE__FK_MM4CMVTEO84WQ24UPFVUCDY08 = ForeignKeys0.IMAGE__FK_MM4CMVTEO84WQ24UPFVUCDY08;
	public static final ForeignKey<ShopUserRolesRecord, ShopUserRecord> SHOP_USER_ROLES__FK_EV613963MJ936X1J1O2FQFXC8 = ForeignKeys0.SHOP_USER_ROLES__FK_EV613963MJ936X1J1O2FQFXC8;
	public static final ForeignKey<СharacteristicValueRecord, СharacteristicRecord> СHARACTERISTIC_VALUE__FK_ISHXS45F8NNOLC8KCP097QGVG = ForeignKeys0.СHARACTERISTIC_VALUE__FK_ISHXS45F8NNOLC8KCP097QGVG;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<CharacteristicRecord> CHARACTERISTIC_PKEY = createUniqueKey(Characteristic.CHARACTERISTIC, Characteristic.CHARACTERISTIC.ID);
		public static final UniqueKey<CharacteristicValueRecord> CHARACTERISTIC_VALUE_PKEY = createUniqueKey(CharacteristicValue.CHARACTERISTIC_VALUE, CharacteristicValue.CHARACTERISTIC_VALUE.ID);
		public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = createUniqueKey(Customer.CUSTOMER, Customer.CUSTOMER.ID);
		public static final UniqueKey<ImageRecord> IMAGE_PKEY = createUniqueKey(Image.IMAGE, Image.IMAGE.ID);
		public static final UniqueKey<MeasurementRecord> MEASUREMENT_PKEY = createUniqueKey(Measurement.MEASUREMENT, Measurement.MEASUREMENT.ID);
		public static final UniqueKey<ProductRecord> PRODUCT_PKEY = createUniqueKey(Product.PRODUCT, Product.PRODUCT.ID);
		public static final UniqueKey<ShopUserRecord> SHOP_USER_PKEY = createUniqueKey(ShopUser.SHOP_USER, ShopUser.SHOP_USER.ID);
		public static final UniqueKey<ShopUserRecord> UK_6REHGURDH18GNR2DBVRYVVDEF = createUniqueKey(ShopUser.SHOP_USER, ShopUser.SHOP_USER.EMAIL);
		public static final UniqueKey<СharacteristicRecord> СHARACTERISTIC_PKEY = createUniqueKey(Сharacteristic.СHARACTERISTIC, Сharacteristic.СHARACTERISTIC.ID);
		public static final UniqueKey<СharacteristicValueRecord> СHARACTERISTIC_VALUE_PKEY = createUniqueKey(СharacteristicValue.СHARACTERISTIC_VALUE, СharacteristicValue.СHARACTERISTIC_VALUE.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<CharacteristicRecord, MeasurementRecord> CHARACTERISTIC__FK_NNSCUVJNXX4K3LEQ8XV03E7V3 = createForeignKey(com.anarbek.shop.dao.domain.jooq.Keys.MEASUREMENT_PKEY, Characteristic.CHARACTERISTIC, Characteristic.CHARACTERISTIC.MEASUREMENT_ID);
		public static final ForeignKey<CharacteristicValueRecord, CharacteristicRecord> CHARACTERISTIC_VALUE__FK_JX672GO7SRNA7S8WJWNYKCLS9 = createForeignKey(com.anarbek.shop.dao.domain.jooq.Keys.CHARACTERISTIC_PKEY, CharacteristicValue.CHARACTERISTIC_VALUE, CharacteristicValue.CHARACTERISTIC_VALUE.CHARACTERISTIC_ID);
		public static final ForeignKey<CharacteristicValueRecord, ProductRecord> CHARACTERISTIC_VALUE__FK_8RVXP5IF9WE3HNY0G41CQFVFN = createForeignKey(com.anarbek.shop.dao.domain.jooq.Keys.PRODUCT_PKEY, CharacteristicValue.CHARACTERISTIC_VALUE, CharacteristicValue.CHARACTERISTIC_VALUE.PRODUCT_ID);
		public static final ForeignKey<ImageRecord, ProductRecord> IMAGE__FK_MM4CMVTEO84WQ24UPFVUCDY08 = createForeignKey(com.anarbek.shop.dao.domain.jooq.Keys.PRODUCT_PKEY, Image.IMAGE, Image.IMAGE.PRODUCT_ID);
		public static final ForeignKey<ShopUserRolesRecord, ShopUserRecord> SHOP_USER_ROLES__FK_EV613963MJ936X1J1O2FQFXC8 = createForeignKey(com.anarbek.shop.dao.domain.jooq.Keys.SHOP_USER_PKEY, ShopUserRoles.SHOP_USER_ROLES, ShopUserRoles.SHOP_USER_ROLES.SHOP_USER_ID);
		public static final ForeignKey<СharacteristicValueRecord, СharacteristicRecord> СHARACTERISTIC_VALUE__FK_ISHXS45F8NNOLC8KCP097QGVG = createForeignKey(com.anarbek.shop.dao.domain.jooq.Keys.СHARACTERISTIC_PKEY, СharacteristicValue.СHARACTERISTIC_VALUE, СharacteristicValue.СHARACTERISTIC_VALUE.СHARACTERISTIC_ID);
	}
}
