/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.domain.jooq;


import com.anarbek.shop.dao.domain.jooq.tables.Characteristic;
import com.anarbek.shop.dao.domain.jooq.tables.CharacteristicValue;
import com.anarbek.shop.dao.domain.jooq.tables.Customer;
import com.anarbek.shop.dao.domain.jooq.tables.Image;
import com.anarbek.shop.dao.domain.jooq.tables.Measurement;
import com.anarbek.shop.dao.domain.jooq.tables.Product;
import com.anarbek.shop.dao.domain.jooq.tables.ShopUser;
import com.anarbek.shop.dao.domain.jooq.tables.ShopUserRoles;
import com.anarbek.shop.dao.domain.jooq.tables.Сharacteristic;
import com.anarbek.shop.dao.domain.jooq.tables.СharacteristicValue;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.characteristic
	 */
	public static final Characteristic CHARACTERISTIC = com.anarbek.shop.dao.domain.jooq.tables.Characteristic.CHARACTERISTIC;

	/**
	 * The table public.characteristic_value
	 */
	public static final CharacteristicValue CHARACTERISTIC_VALUE = com.anarbek.shop.dao.domain.jooq.tables.CharacteristicValue.CHARACTERISTIC_VALUE;

	/**
	 * The table public.customer
	 */
	public static final Customer CUSTOMER = com.anarbek.shop.dao.domain.jooq.tables.Customer.CUSTOMER;

	/**
	 * The table public.image
	 */
	public static final Image IMAGE = com.anarbek.shop.dao.domain.jooq.tables.Image.IMAGE;

	/**
	 * The table public.measurement
	 */
	public static final Measurement MEASUREMENT = com.anarbek.shop.dao.domain.jooq.tables.Measurement.MEASUREMENT;

	/**
	 * The table public.product
	 */
	public static final Product PRODUCT = com.anarbek.shop.dao.domain.jooq.tables.Product.PRODUCT;

	/**
	 * The table public.shop_user
	 */
	public static final ShopUser SHOP_USER = com.anarbek.shop.dao.domain.jooq.tables.ShopUser.SHOP_USER;

	/**
	 * The table public.shop_user_roles
	 */
	public static final ShopUserRoles SHOP_USER_ROLES = com.anarbek.shop.dao.domain.jooq.tables.ShopUserRoles.SHOP_USER_ROLES;

	/**
	 * The table public.сharacteristic
	 */
	public static final Сharacteristic СHARACTERISTIC = com.anarbek.shop.dao.domain.jooq.tables.Сharacteristic.СHARACTERISTIC;

	/**
	 * The table public.сharacteristic_value
	 */
	public static final СharacteristicValue СHARACTERISTIC_VALUE = com.anarbek.shop.dao.domain.jooq.tables.СharacteristicValue.СHARACTERISTIC_VALUE;
}
