/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.domain.jooq.tables.records;


import com.anarbek.shop.dao.domain.jooq.tables.CharacteristicValue;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacteristicValueRecord extends UpdatableRecordImpl<CharacteristicValueRecord> implements Record6<Long, Timestamp, Double, String, Long, Long> {

	private static final long serialVersionUID = 2135375015;

	/**
	 * Setter for <code>public.characteristic_value.id</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.characteristic_value.id</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>public.characteristic_value.date_value</code>.
	 */
	public void setDateValue(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.characteristic_value.date_value</code>.
	 */
	public Timestamp getDateValue() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>public.characteristic_value.double_value</code>.
	 */
	public void setDoubleValue(Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.characteristic_value.double_value</code>.
	 */
	public Double getDoubleValue() {
		return (Double) getValue(2);
	}

	/**
	 * Setter for <code>public.characteristic_value.string_value</code>.
	 */
	public void setStringValue(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.characteristic_value.string_value</code>.
	 */
	public String getStringValue() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.characteristic_value.characteristic_id</code>.
	 */
	public void setCharacteristicId(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.characteristic_value.characteristic_id</code>.
	 */
	public Long getCharacteristicId() {
		return (Long) getValue(4);
	}

	/**
	 * Setter for <code>public.characteristic_value.product_id</code>.
	 */
	public void setProductId(Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.characteristic_value.product_id</code>.
	 */
	public Long getProductId() {
		return (Long) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, Timestamp, Double, String, Long, Long> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, Timestamp, Double, String, Long, Long> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return CharacteristicValue.CHARACTERISTIC_VALUE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return CharacteristicValue.CHARACTERISTIC_VALUE.DATE_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field3() {
		return CharacteristicValue.CHARACTERISTIC_VALUE.DOUBLE_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return CharacteristicValue.CHARACTERISTIC_VALUE.STRING_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return CharacteristicValue.CHARACTERISTIC_VALUE.CHARACTERISTIC_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return CharacteristicValue.CHARACTERISTIC_VALUE.PRODUCT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getDateValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value3() {
		return getDoubleValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getStringValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getCharacteristicId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getProductId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacteristicValueRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacteristicValueRecord value2(Timestamp value) {
		setDateValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacteristicValueRecord value3(Double value) {
		setDoubleValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacteristicValueRecord value4(String value) {
		setStringValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacteristicValueRecord value5(Long value) {
		setCharacteristicId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacteristicValueRecord value6(Long value) {
		setProductId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CharacteristicValueRecord values(Long value1, Timestamp value2, Double value3, String value4, Long value5, Long value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CharacteristicValueRecord
	 */
	public CharacteristicValueRecord() {
		super(CharacteristicValue.CHARACTERISTIC_VALUE);
	}

	/**
	 * Create a detached, initialised CharacteristicValueRecord
	 */
	public CharacteristicValueRecord(Long id, Timestamp dateValue, Double doubleValue, String stringValue, Long characteristicId, Long productId) {
		super(CharacteristicValue.CHARACTERISTIC_VALUE);

		setValue(0, id);
		setValue(1, dateValue);
		setValue(2, doubleValue);
		setValue(3, stringValue);
		setValue(4, characteristicId);
		setValue(5, productId);
	}
}
