/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.domain.jooq.tables.records;


import com.anarbek.shop.dao.domain.jooq.tables.ShopUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopUserRecord extends UpdatableRecordImpl<ShopUserRecord> implements Record7<Long, Boolean, Boolean, Boolean, String, Boolean, String> {

	private static final long serialVersionUID = 405802908;

	/**
	 * Setter for <code>public.shop_user.id</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.shop_user.id</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>public.shop_user.account_non_expired</code>.
	 */
	public void setAccountNonExpired(Boolean value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.shop_user.account_non_expired</code>.
	 */
	public Boolean getAccountNonExpired() {
		return (Boolean) getValue(1);
	}

	/**
	 * Setter for <code>public.shop_user.account_mon_locked</code>.
	 */
	public void setAccountMonLocked(Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.shop_user.account_mon_locked</code>.
	 */
	public Boolean getAccountMonLocked() {
		return (Boolean) getValue(2);
	}

	/**
	 * Setter for <code>public.shop_user.credentials_non_expired</code>.
	 */
	public void setCredentialsNonExpired(Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.shop_user.credentials_non_expired</code>.
	 */
	public Boolean getCredentialsNonExpired() {
		return (Boolean) getValue(3);
	}

	/**
	 * Setter for <code>public.shop_user.email</code>.
	 */
	public void setEmail(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.shop_user.email</code>.
	 */
	public String getEmail() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.shop_user.enabled</code>.
	 */
	public void setEnabled(Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.shop_user.enabled</code>.
	 */
	public Boolean getEnabled() {
		return (Boolean) getValue(5);
	}

	/**
	 * Setter for <code>public.shop_user.password</code>.
	 */
	public void setPassword(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.shop_user.password</code>.
	 */
	public String getPassword() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Boolean, Boolean, Boolean, String, Boolean, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Boolean, Boolean, Boolean, String, Boolean, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return ShopUser.SHOP_USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field2() {
		return ShopUser.SHOP_USER.ACCOUNT_NON_EXPIRED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field3() {
		return ShopUser.SHOP_USER.ACCOUNT_MON_LOCKED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return ShopUser.SHOP_USER.CREDENTIALS_NON_EXPIRED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return ShopUser.SHOP_USER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field6() {
		return ShopUser.SHOP_USER.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return ShopUser.SHOP_USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value2() {
		return getAccountNonExpired();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value3() {
		return getAccountMonLocked();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getCredentialsNonExpired();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value6() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRecord value2(Boolean value) {
		setAccountNonExpired(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRecord value3(Boolean value) {
		setAccountMonLocked(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRecord value4(Boolean value) {
		setCredentialsNonExpired(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRecord value5(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRecord value6(Boolean value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRecord value7(String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRecord values(Long value1, Boolean value2, Boolean value3, Boolean value4, String value5, Boolean value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ShopUserRecord
	 */
	public ShopUserRecord() {
		super(ShopUser.SHOP_USER);
	}

	/**
	 * Create a detached, initialised ShopUserRecord
	 */
	public ShopUserRecord(Long id, Boolean accountNonExpired, Boolean accountMonLocked, Boolean credentialsNonExpired, String email, Boolean enabled, String password) {
		super(ShopUser.SHOP_USER);

		setValue(0, id);
		setValue(1, accountNonExpired);
		setValue(2, accountMonLocked);
		setValue(3, credentialsNonExpired);
		setValue(4, email);
		setValue(5, enabled);
		setValue(6, password);
	}
}
