/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.domain.jooq.tables.records;


import com.anarbek.shop.dao.domain.jooq.tables.ShopUserRoles;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopUserRolesRecord extends TableRecordImpl<ShopUserRolesRecord> implements Record2<Long, String> {

	private static final long serialVersionUID = 2118199086;

	/**
	 * Setter for <code>public.shop_user_roles.shop_user_id</code>.
	 */
	public void setShopUserId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.shop_user_roles.shop_user_id</code>.
	 */
	public Long getShopUserId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>public.shop_user_roles.roles</code>.
	 */
	public void setRoles(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.shop_user_roles.roles</code>.
	 */
	public String getRoles() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return ShopUserRoles.SHOP_USER_ROLES.SHOP_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ShopUserRoles.SHOP_USER_ROLES.ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getShopUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getRoles();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRolesRecord value1(Long value) {
		setShopUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRolesRecord value2(String value) {
		setRoles(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRolesRecord values(Long value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ShopUserRolesRecord
	 */
	public ShopUserRolesRecord() {
		super(ShopUserRoles.SHOP_USER_ROLES);
	}

	/**
	 * Create a detached, initialised ShopUserRolesRecord
	 */
	public ShopUserRolesRecord(Long shopUserId, String roles) {
		super(ShopUserRoles.SHOP_USER_ROLES);

		setValue(0, shopUserId);
		setValue(1, roles);
	}
}
