/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.jooq;


import com.anarbek.shop.dao.jooq.tables.Customer;
import com.anarbek.shop.dao.jooq.tables.Image;
import com.anarbek.shop.dao.jooq.tables.Measurement;
import com.anarbek.shop.dao.jooq.tables.Product;
import com.anarbek.shop.dao.jooq.tables.ProductCharacteristic;
import com.anarbek.shop.dao.jooq.tables.ProductCharacteristicValue;
import com.anarbek.shop.dao.jooq.tables.ShopUser;
import com.anarbek.shop.dao.jooq.tables.ShopUserRoles;
import com.anarbek.shop.dao.jooq.tables.records.CustomerRecord;
import com.anarbek.shop.dao.jooq.tables.records.ImageRecord;
import com.anarbek.shop.dao.jooq.tables.records.MeasurementRecord;
import com.anarbek.shop.dao.jooq.tables.records.ProductCharacteristicRecord;
import com.anarbek.shop.dao.jooq.tables.records.ProductCharacteristicValueRecord;
import com.anarbek.shop.dao.jooq.tables.records.ProductRecord;
import com.anarbek.shop.dao.jooq.tables.records.ShopUserRecord;
import com.anarbek.shop.dao.jooq.tables.records.ShopUserRolesRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = UniqueKeys0.CUSTOMER_PKEY;
	public static final UniqueKey<ImageRecord> IMAGE_PKEY = UniqueKeys0.IMAGE_PKEY;
	public static final UniqueKey<MeasurementRecord> MEASUREMENT_PKEY = UniqueKeys0.MEASUREMENT_PKEY;
	public static final UniqueKey<ProductRecord> PRODUCT_PKEY = UniqueKeys0.PRODUCT_PKEY;
	public static final UniqueKey<ProductCharacteristicRecord> PRODUCT_CHARACTERISTIC_PKEY = UniqueKeys0.PRODUCT_CHARACTERISTIC_PKEY;
	public static final UniqueKey<ProductCharacteristicValueRecord> PRODUCT_CHARACTERISTIC_VALUE_PKEY = UniqueKeys0.PRODUCT_CHARACTERISTIC_VALUE_PKEY;
	public static final UniqueKey<ShopUserRecord> SHOP_USER_PKEY = UniqueKeys0.SHOP_USER_PKEY;
	public static final UniqueKey<ShopUserRecord> UK_6REHGURDH18GNR2DBVRYVVDEF = UniqueKeys0.UK_6REHGURDH18GNR2DBVRYVVDEF;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<ImageRecord, ProductRecord> IMAGE__FK_MM4CMVTEO84WQ24UPFVUCDY08 = ForeignKeys0.IMAGE__FK_MM4CMVTEO84WQ24UPFVUCDY08;
	public static final ForeignKey<ProductCharacteristicRecord, MeasurementRecord> PRODUCT_CHARACTERISTIC__FK_Y2U4V1ANJIW8EGN4OCL7H0TC = ForeignKeys0.PRODUCT_CHARACTERISTIC__FK_Y2U4V1ANJIW8EGN4OCL7H0TC;
	public static final ForeignKey<ProductCharacteristicValueRecord, ProductCharacteristicRecord> PRODUCT_CHARACTERISTIC_VALUE__FK_LC5H95N3Y1W48B91F0V7644ON = ForeignKeys0.PRODUCT_CHARACTERISTIC_VALUE__FK_LC5H95N3Y1W48B91F0V7644ON;
	public static final ForeignKey<ProductCharacteristicValueRecord, ProductRecord> PRODUCT_CHARACTERISTIC_VALUE__FK_QAGQ5VITLRJ12YQ563BSJEFAI = ForeignKeys0.PRODUCT_CHARACTERISTIC_VALUE__FK_QAGQ5VITLRJ12YQ563BSJEFAI;
	public static final ForeignKey<ShopUserRolesRecord, ShopUserRecord> SHOP_USER_ROLES__FK_EV613963MJ936X1J1O2FQFXC8 = ForeignKeys0.SHOP_USER_ROLES__FK_EV613963MJ936X1J1O2FQFXC8;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = createUniqueKey(Customer.CUSTOMER, Customer.CUSTOMER.ID);
		public static final UniqueKey<ImageRecord> IMAGE_PKEY = createUniqueKey(Image.IMAGE, Image.IMAGE.ID);
		public static final UniqueKey<MeasurementRecord> MEASUREMENT_PKEY = createUniqueKey(Measurement.MEASUREMENT, Measurement.MEASUREMENT.ID);
		public static final UniqueKey<ProductRecord> PRODUCT_PKEY = createUniqueKey(Product.PRODUCT, Product.PRODUCT.ID);
		public static final UniqueKey<ProductCharacteristicRecord> PRODUCT_CHARACTERISTIC_PKEY = createUniqueKey(ProductCharacteristic.PRODUCT_CHARACTERISTIC, ProductCharacteristic.PRODUCT_CHARACTERISTIC.ID);
		public static final UniqueKey<ProductCharacteristicValueRecord> PRODUCT_CHARACTERISTIC_VALUE_PKEY = createUniqueKey(ProductCharacteristicValue.PRODUCT_CHARACTERISTIC_VALUE, ProductCharacteristicValue.PRODUCT_CHARACTERISTIC_VALUE.ID);
		public static final UniqueKey<ShopUserRecord> SHOP_USER_PKEY = createUniqueKey(ShopUser.SHOP_USER, ShopUser.SHOP_USER.ID);
		public static final UniqueKey<ShopUserRecord> UK_6REHGURDH18GNR2DBVRYVVDEF = createUniqueKey(ShopUser.SHOP_USER, ShopUser.SHOP_USER.EMAIL);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<ImageRecord, ProductRecord> IMAGE__FK_MM4CMVTEO84WQ24UPFVUCDY08 = createForeignKey(com.anarbek.shop.dao.jooq.Keys.PRODUCT_PKEY, Image.IMAGE, Image.IMAGE.PRODUCT_ID);
		public static final ForeignKey<ProductCharacteristicRecord, MeasurementRecord> PRODUCT_CHARACTERISTIC__FK_Y2U4V1ANJIW8EGN4OCL7H0TC = createForeignKey(com.anarbek.shop.dao.jooq.Keys.MEASUREMENT_PKEY, ProductCharacteristic.PRODUCT_CHARACTERISTIC, ProductCharacteristic.PRODUCT_CHARACTERISTIC.MEASUREMENT_ID);
		public static final ForeignKey<ProductCharacteristicValueRecord, ProductCharacteristicRecord> PRODUCT_CHARACTERISTIC_VALUE__FK_LC5H95N3Y1W48B91F0V7644ON = createForeignKey(com.anarbek.shop.dao.jooq.Keys.PRODUCT_CHARACTERISTIC_PKEY, ProductCharacteristicValue.PRODUCT_CHARACTERISTIC_VALUE, ProductCharacteristicValue.PRODUCT_CHARACTERISTIC_VALUE.CHARACTERISTIC_ID);
		public static final ForeignKey<ProductCharacteristicValueRecord, ProductRecord> PRODUCT_CHARACTERISTIC_VALUE__FK_QAGQ5VITLRJ12YQ563BSJEFAI = createForeignKey(com.anarbek.shop.dao.jooq.Keys.PRODUCT_PKEY, ProductCharacteristicValue.PRODUCT_CHARACTERISTIC_VALUE, ProductCharacteristicValue.PRODUCT_CHARACTERISTIC_VALUE.PRODUCT_ID);
		public static final ForeignKey<ShopUserRolesRecord, ShopUserRecord> SHOP_USER_ROLES__FK_EV613963MJ936X1J1O2FQFXC8 = createForeignKey(com.anarbek.shop.dao.jooq.Keys.SHOP_USER_PKEY, ShopUserRoles.SHOP_USER_ROLES, ShopUserRoles.SHOP_USER_ROLES.SHOP_USER_ID);
	}
}
