/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.jooq;


import com.anarbek.shop.dao.jooq.tables.Customer;
import com.anarbek.shop.dao.jooq.tables.Image;
import com.anarbek.shop.dao.jooq.tables.Measurement;
import com.anarbek.shop.dao.jooq.tables.Product;
import com.anarbek.shop.dao.jooq.tables.ProductCharacteristic;
import com.anarbek.shop.dao.jooq.tables.ProductCharacteristicValue;
import com.anarbek.shop.dao.jooq.tables.ShopUser;
import com.anarbek.shop.dao.jooq.tables.ShopUserRoles;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.customer
	 */
	public static final Customer CUSTOMER = com.anarbek.shop.dao.jooq.tables.Customer.CUSTOMER;

	/**
	 * The table public.image
	 */
	public static final Image IMAGE = com.anarbek.shop.dao.jooq.tables.Image.IMAGE;

	/**
	 * The table public.measurement
	 */
	public static final Measurement MEASUREMENT = com.anarbek.shop.dao.jooq.tables.Measurement.MEASUREMENT;

	/**
	 * The table public.product
	 */
	public static final Product PRODUCT = com.anarbek.shop.dao.jooq.tables.Product.PRODUCT;

	/**
	 * The table public.product_characteristic
	 */
	public static final ProductCharacteristic PRODUCT_CHARACTERISTIC = com.anarbek.shop.dao.jooq.tables.ProductCharacteristic.PRODUCT_CHARACTERISTIC;

	/**
	 * The table public.product_characteristic_value
	 */
	public static final ProductCharacteristicValue PRODUCT_CHARACTERISTIC_VALUE = com.anarbek.shop.dao.jooq.tables.ProductCharacteristicValue.PRODUCT_CHARACTERISTIC_VALUE;

	/**
	 * The table public.shop_user
	 */
	public static final ShopUser SHOP_USER = com.anarbek.shop.dao.jooq.tables.ShopUser.SHOP_USER;

	/**
	 * The table public.shop_user_roles
	 */
	public static final ShopUserRoles SHOP_USER_ROLES = com.anarbek.shop.dao.jooq.tables.ShopUserRoles.SHOP_USER_ROLES;
}
