/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.jooq.tables;


import com.anarbek.shop.dao.jooq.Keys;
import com.anarbek.shop.dao.jooq.Public;
import com.anarbek.shop.dao.jooq.tables.records.ProductCharacteristicValueRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCharacteristicValue extends TableImpl<ProductCharacteristicValueRecord> {

	private static final long serialVersionUID = -1364994988;

	/**
	 * The reference instance of <code>public.product_characteristic_value</code>
	 */
	public static final ProductCharacteristicValue PRODUCT_CHARACTERISTIC_VALUE = new ProductCharacteristicValue();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ProductCharacteristicValueRecord> getRecordType() {
		return ProductCharacteristicValueRecord.class;
	}

	/**
	 * The column <code>public.product_characteristic_value.id</code>.
	 */
	public final TableField<ProductCharacteristicValueRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.product_characteristic_value.date_value</code>.
	 */
	public final TableField<ProductCharacteristicValueRecord, Timestamp> DATE_VALUE = createField("date_value", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.product_characteristic_value.double_value</code>.
	 */
	public final TableField<ProductCharacteristicValueRecord, Double> DOUBLE_VALUE = createField("double_value", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>public.product_characteristic_value.string_value</code>.
	 */
	public final TableField<ProductCharacteristicValueRecord, String> STRING_VALUE = createField("string_value", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.product_characteristic_value.characteristic_id</code>.
	 */
	public final TableField<ProductCharacteristicValueRecord, Long> CHARACTERISTIC_ID = createField("characteristic_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.product_characteristic_value.product_id</code>.
	 */
	public final TableField<ProductCharacteristicValueRecord, Long> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.product_characteristic_value</code> table reference
	 */
	public ProductCharacteristicValue() {
		this("product_characteristic_value", null);
	}

	/**
	 * Create an aliased <code>public.product_characteristic_value</code> table reference
	 */
	public ProductCharacteristicValue(String alias) {
		this(alias, PRODUCT_CHARACTERISTIC_VALUE);
	}

	private ProductCharacteristicValue(String alias, Table<ProductCharacteristicValueRecord> aliased) {
		this(alias, aliased, null);
	}

	private ProductCharacteristicValue(String alias, Table<ProductCharacteristicValueRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ProductCharacteristicValueRecord> getPrimaryKey() {
		return Keys.PRODUCT_CHARACTERISTIC_VALUE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ProductCharacteristicValueRecord>> getKeys() {
		return Arrays.<UniqueKey<ProductCharacteristicValueRecord>>asList(Keys.PRODUCT_CHARACTERISTIC_VALUE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ProductCharacteristicValueRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ProductCharacteristicValueRecord, ?>>asList(Keys.PRODUCT_CHARACTERISTIC_VALUE__FK_LC5H95N3Y1W48B91F0V7644ON, Keys.PRODUCT_CHARACTERISTIC_VALUE__FK_QAGQ5VITLRJ12YQ563BSJEFAI);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProductCharacteristicValue as(String alias) {
		return new ProductCharacteristicValue(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ProductCharacteristicValue rename(String name) {
		return new ProductCharacteristicValue(name, null);
	}
}
