/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.jooq.tables;


import com.anarbek.shop.dao.jooq.Keys;
import com.anarbek.shop.dao.jooq.Public;
import com.anarbek.shop.dao.jooq.tables.records.ShopUserRolesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopUserRoles extends TableImpl<ShopUserRolesRecord> {

	private static final long serialVersionUID = -828485296;

	/**
	 * The reference instance of <code>public.shop_user_roles</code>
	 */
	public static final ShopUserRoles SHOP_USER_ROLES = new ShopUserRoles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ShopUserRolesRecord> getRecordType() {
		return ShopUserRolesRecord.class;
	}

	/**
	 * The column <code>public.shop_user_roles.shop_user_id</code>.
	 */
	public final TableField<ShopUserRolesRecord, Long> SHOP_USER_ID = createField("shop_user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.shop_user_roles.roles</code>.
	 */
	public final TableField<ShopUserRolesRecord, String> ROLES = createField("roles", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>public.shop_user_roles</code> table reference
	 */
	public ShopUserRoles() {
		this("shop_user_roles", null);
	}

	/**
	 * Create an aliased <code>public.shop_user_roles</code> table reference
	 */
	public ShopUserRoles(String alias) {
		this(alias, SHOP_USER_ROLES);
	}

	private ShopUserRoles(String alias, Table<ShopUserRolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ShopUserRoles(String alias, Table<ShopUserRolesRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ShopUserRolesRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ShopUserRolesRecord, ?>>asList(Keys.SHOP_USER_ROLES__FK_EV613963MJ936X1J1O2FQFXC8);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ShopUserRoles as(String alias) {
		return new ShopUserRoles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ShopUserRoles rename(String name) {
		return new ShopUserRoles(name, null);
	}
}
