/**
 * This class is generated by jOOQ
 */
package com.anarbek.shop.dao.domain.jooq.tables;


import com.anarbek.shop.dao.domain.jooq.Keys;
import com.anarbek.shop.dao.domain.jooq.Public;
import com.anarbek.shop.dao.domain.jooq.tables.records.CharacteristicRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Characteristic extends TableImpl<CharacteristicRecord> {

	private static final long serialVersionUID = 1575856081;

	/**
	 * The reference instance of <code>public.characteristic</code>
	 */
	public static final Characteristic CHARACTERISTIC = new Characteristic();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CharacteristicRecord> getRecordType() {
		return CharacteristicRecord.class;
	}

	/**
	 * The column <code>public.characteristic.id</code>.
	 */
	public final TableField<CharacteristicRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.characteristic.characteristic_type</code>.
	 */
	public final TableField<CharacteristicRecord, String> CHARACTERISTIC_TYPE = createField("characteristic_type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.characteristic.description</code>.
	 */
	public final TableField<CharacteristicRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>public.characteristic.title</code>.
	 */
	public final TableField<CharacteristicRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * The column <code>public.characteristic.measurement_id</code>.
	 */
	public final TableField<CharacteristicRecord, Long> MEASUREMENT_ID = createField("measurement_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.characteristic</code> table reference
	 */
	public Characteristic() {
		this("characteristic", null);
	}

	/**
	 * Create an aliased <code>public.characteristic</code> table reference
	 */
	public Characteristic(String alias) {
		this(alias, CHARACTERISTIC);
	}

	private Characteristic(String alias, Table<CharacteristicRecord> aliased) {
		this(alias, aliased, null);
	}

	private Characteristic(String alias, Table<CharacteristicRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CharacteristicRecord> getPrimaryKey() {
		return Keys.CHARACTERISTIC_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CharacteristicRecord>> getKeys() {
		return Arrays.<UniqueKey<CharacteristicRecord>>asList(Keys.CHARACTERISTIC_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<CharacteristicRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<CharacteristicRecord, ?>>asList(Keys.CHARACTERISTIC__FK_NNSCUVJNXX4K3LEQ8XV03E7V3);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Characteristic as(String alias) {
		return new Characteristic(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Characteristic rename(String name) {
		return new Characteristic(name, null);
	}
}
